### PR TITLE
Rebuild protobuf parser using protoc 25.1

### PR DESCRIPTION
**Pull request by jameinel**
This rebuilds the Bakery making it compatible with Protobuf >= 3.20 (including 4.*)

The issue is that Builder objects were introduced in 3.20 and are mandatory for 4.* support. So if you regenerate the protocol definition to support 4.* then it won't import with 3.4 or 3.19 (as I tested).

This appears to work with both 4.0 and 3.20 at least. I don't know what versions of Protobuf we need to support.

### CODE REVIEW

**Comment by gboutry** [comment]
This would also require bumping https://github.com/go-macaroon-bakery/py-macaroon-bakery/blob/59caade716f8d4591524837c8a506827d487f049/setup.py#L30C1-L30C23

**Comment by fabricematrat** [comment]
@jameinel you should also modify the setup.py.

**Comment by jameinel** [comment]
I updated setup.py as well.

**Comment by cderici** [comment]
@fabricematrat pinging for this anytime you can ☝️ thanks again for all the time you spent on this! ❤️

**Pull request merged**
